name: winit
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip:
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - axial-positional-embedding==0.3.12
      - captum==0.4.0
      - cffi==1.17.1
      - colt5-attention==0.11.1
      - cryptography==45.0.3
      - distro==1.9.0
      - einops==0.8.1
      - fsspec==2025.5.1
      - git-filter-repo==2.47.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyper-connections==0.1.15
      - ipdb==0.13.13
      - jinja2==3.1.6
      - jitcxde-common==1.4.1
      - jiter==0.10.0
      - joblib==1.5.1
      - llvmlite==0.43.0
      - local-attention==1.11.1
      - markupsafe==3.0.2
      - matplotlib==3.6.0
      - mpmath==1.3.0
      - numba==0.60.0
      - numpy==1.22.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - openai==1.82.0
      - pandas==1.3.5
      - pdfminer-six==20250327
      - pdfplumber==0.11.6
      - product-key-memory==0.2.11
      - pycparser==2.22
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pypdf==5.5.0
      - pypdf2==3.0.1
      - pypdfium2==4.30.1
      - reformer-pytorch==1.4.4
      - scikit-learn==1.1.2
      - scipy==1.6.2
      - seaborn==0.12.1
      - sniffio==1.3.1
      - symengine==0.14.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timesynth==0.2.4
      - torch==2.7.1
      - tqdm==4.67.1
      - triton==3.3.1
      - tslearn==0.6.3
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
# prefix: /home/anaconda3/envs/winit
